In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, train_test_split
#format for print 
np.set_printoptions(formatter={'float':"{:6.11g}".format})

mv=pd.read_csv('../BaseContent/input/tmdb_5000_movies.csv')
rating=pd.read_csv('../BaseContent/input/ratings_small.csv')

In [2]:
# print(rating.shape)
# rating = rating[rating["movieId"] < 48665 ].reset_index(drop=True)
# print(rating.shape)
# divide train and test set
rating_train, rating_test = train_test_split(
    rating, test_size=0.15, random_state=42)

train_set = rating_train.values
test_set = rating_test.values

print(train_set.shape)
print(test_set.shape)

(85003, 4)
(15001, 4)


In [3]:
# Change genres column to define genres list 
from ast import literal_eval


features = ['genres']
for feature in features:
    mv[feature] = mv[feature].apply(literal_eval)
  
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        #Check if more than 3 elements exist. If yes, return only first three. If no, return entire list.
        if len(names) > 3:
            names = names[:3]
        return names
    #Return empty list in case of missing/malformed data
    return []

features = ['genres']

for feature in features:
    mv[feature] = mv[feature].apply(get_list)
    
mv.head(5)


budget                                genres  \
0  237000000          [Action, Adventure, Fantasy]   
1  300000000          [Adventure, Fantasy, Action]   
2  245000000            [Action, Adventure, Crime]   
3  250000000                [Action, Crime, Drama]   
4  260000000  [Action, Adventure, Science Fiction]   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [4]:
mv.head(5)

budget                                genres  \
0  237000000          [Action, Adventure, Fantasy]   
1  300000000          [Adventure, Fantasy, Action]   
2  245000000            [Action, Adventure, Crime]   
3  250000000                [Action, Crime, Drama]   
4  260000000  [Action, Adventure, Science Fiction]   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [77]:
# Change genres column into others column and id movie 
columns_genres = ['id', 'unknown', 'Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
                  'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
genres_dataframe = pd.DataFrame(columns=columns_genres)
for index in mv.index:
    
    value = mv['id'][index]
    tmp = [value]

features = ['genres']
for feature in features:
    mv[feature] = mv[feature].apply(literal_eval)
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        #Check if more than 3 elements exist. If yes, return only first three. If no, return entire list.
        if len(names) > 3:
            names = names[:3]
        return names
    #Return empty list in case of missing/malformed data
    return []

features = ['genres','keywords']
mv = changedata(mv)
for feature in features:
    mv[feature] = mv[feature].apply(get_list)
    
mv.head(3)

(4803, 20)

In [5]:
#change to tfidf create feature vector for items

from sklearn.feature_extraction.text import TfidfTransformer
transformer = TfidfTransformer(smooth_idf=True, norm ='l2')
tfidf = transformer.fit_transform(X_train_counts.tolist()).toarray()
print(tfidf)

NameError: name 'df2' is not defined

In [110]:
import joblib

def store_model(model, model_name=""):
    # NOTE: sklearn.joblib faster than pickle of Python
    # INFO: can store only ONE object in a file
    if model_name == "":
        model_name = type(model).__name__
    joblib.dump(model, '../BaseContent/' + model_name + '_model.pkl')


def load_model(model_name):
    # Load objects into memory
    #del model
    model = joblib.load('../BaseContent/' + model_name + '_model.pkl')
    # print(model)
    return model

In [95]:
# get movie that rated by user
np.set_printoptions(formatter={'float': "{:6.11g}".format})


def get_items_rated_by_user(rate_matrix, user_id):
    """
    in each line of rate_matrix, we have infor: user_id, item_id, rating (scores), time_stamp
    we care about the first three values
    return (item_ids, scores) rated by user user_id

    """
    y = rate_matrix[:, 0]  # all users

    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1
    # while index in python starts from 0

    ids = np.where(y == (user_id + 1))[0]
    tmp_ids = []
    for item in ids:
        if item.size > 0:
            tmp_ids.append(item)
    
    item_ids = rate_matrix[tmp_ids, 1] - 1  # index starts from 0

    scores = rate_matrix[tmp_ids, 2]
    # print(ids)
    return (item_ids, scores)


In [139]:
from sklearn.linear_model import Ridge
from sklearn import linear_model

d = tfidf.shape[1] # data dimension
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))


for n in range(n_users):    
    ids, scores = get_items_rated_by_user(train_set, n)
    ids = ids.astype(int)
 
    clf = Ridge(alpha=0.01, fit_intercept  = True)
    
    Xhat = tfidf[ids, :]
    clf.fit(Xhat, scores)

    W[:, n] = clf.coef_
    b[0, n] = clf.intercept_
store_model(clf)

In [140]:


Yhat = tfidf.dot(W) + b
print(Yhat)

[[2.48 3.56 3.41 ... 4.98 4.6  4.28]
 [2.48 3.56 3.41 ... 4.98 4.6  4.28]
 [1.52 3.61 3.46 ... 6.42 4.33 3.66]
 ...
 [2.87 3.23 3.29 ... 2.82 2.97 5.12]
 [2.91 3.92 3.81 ... 4.48 2.   2.33]
 [2.91 4.   3.81 ... 4.48 3.98 2.33]]


In [178]:
# Test load model for api

model = load_model("Ridge")

tmp  = [
    [0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0],
    [0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0]
]
columns_genres_test_load = ['unknown', 'Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
                  'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
genres_dataframe_test_load = pd.DataFrame( tmp,columns=columns_genres_test_load)

# print(genres_dataframe_test_load)
X1 = genres_dataframe_test_load.values

yhat = model.predict(X1)
print(yhat)

[3.44 5.49]


In [179]:
n = 1
np.set_printoptions(precision=2) 
ids, scores = get_items_rated_by_user(train_set, n)
ids = ids.astype(int)
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

Rated movies ids : [585 316 719 167 184 584 370 234 514 272 473 369 160 295  46 264 222 499
 456 381 409 152 479 318 588 591 589  51 260 592 538 271 371 549 507 149
 355 551 363  49 453 252 586 526 299 356 660   9  61 376 109  38 265 291
 349 313 207 484 221 615  16 143 496 404 366 508 348]
True ratings     : [3. 2. 4. 3. 3. 5. 3. 3. 4. 4. 2. 2. 3. 4. 4. 5. 1. 4. 3. 3. 3. 4. 4. 1.
 5. 5. 5. 3. 4. 3. 3. 3. 3. 3. 4. 5. 3. 3. 3. 4. 4. 4. 3. 4. 3. 3. 4. 4.
 3. 3. 4. 5. 5. 3. 4. 4. 3. 3. 5. 3. 5. 3. 3. 2. 3. 4. 4.]
Predicted ratings: [3.08 3.61 4.   3.32 3.44 3.82 3.32 3.55 3.39 3.47 3.58 3.56 3.56 3.41
 3.56 3.28 2.9  3.41 2.82 3.4  3.28 3.4  3.73 3.39 3.61 3.84 4.97 3.52
 3.52 3.71 3.01 3.41 3.41 3.92 3.52 3.41 3.41 3.67 3.71 3.43 3.25 3.25
 3.08 3.28 3.5  3.61 3.28 3.56 3.4  2.9  3.93 3.56 3.58 3.62 3.47 3.59
 3.52 3.71 3.73 3.25 3.52 3.93 3.39 3.43 3.41 3.52 3.39]


In [87]:
from math import sqrt
def evaluate(Yhat, rates, W, b):
    se = 0
    cnt = 0
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        ids = ids.astype(int)
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred 
        se += (e*e).sum(axis = 0)
        cnt += e.size 
    return sqrt(se/cnt)

In [183]:
print('RMSE for training:', evaluate(Yhat, train_set, W, b))
print('RMSE for test    :', evaluate(Yhat, test_set, W, b))


RMSE for training: 0.8969094630287071
RMSE for test    : 1.0785183992932756
