In [12]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, train_test_split
#format for print 
np.set_printoptions(formatter={'float':"{:6.11g}".format})

mv=pd.read_csv('../BaseContent/input/tmdb_5000_movies.csv')
rating=pd.read_csv('../BaseContent/input/ratings_small - Copy.csv')

In [3]:
# print(rating.shape)
# rating = rating[rating["movieId"] < 48665 ].reset_index(drop=True)
# print(rating.shape)
# divide train and test set
rating_train, rating_test = train_test_split(
    rating, test_size=0.15, random_state=42)

train_set = rating_train.values
test_set = rating_test.values

print(train_set.shape)
print(rating_test)

n_users = 600

(61014, 4)
       userId  movieId  rating   timestamp
18209     185     2137     3.0  1019787081
46243     461     2001     3.0  1091959030
10571     102      858     5.0   956598493
32516     318     1367     2.0   862902909
7625       73     2724     2.5  1304412607
...       ...      ...     ...         ...
27888     285      736     2.0   965091630
39999     405      349     4.0  1097769146
53086     518      502     3.0   945369348
7757       73     3826     1.5  1257229260
59301     564      348     4.0   974712445

[10768 rows x 4 columns]


In [15]:
# Change genres column to define genres list 
from ast import literal_eval


features = ['genres']
for feature in features:
    mv[feature] = mv[feature].apply(literal_eval)
  
def get_list(x):
    if isinstance(x, list):
        names = [i['name'] for i in x]
        #Check if more than 3 elements exist. If yes, return only first three. If no, return entire list.
        if len(names) > 3:
            names = names[:3]
        return names
    #Return empty list in case of missing/malformed data
    return []

features = ['genres']

for feature in features:
    mv[feature] = mv[feature].apply(get_list)
    
mv.head(5)



         budget                                      genres  \
0     237000000          ['Action', 'Adventure', 'Fantasy']   
1     300000000          ['Adventure', 'Fantasy', 'Action']   
2     245000000            ['Action', 'Adventure', 'Crime']   
3     250000000                ['Action', 'Crime', 'Drama']   
4     260000000  ['Action', 'Adventure', 'Science Fiction']   
...         ...                                         ...   
4798     220000             ['Action', 'Crime', 'Thriller']   
4799       9000                       ['Comedy', 'Romance']   
4800          0              ['Comedy', 'Drama', 'Romance']   
4801          0                                          []   
4802          0                             ['Documentary']   

                                               homepage      id  \
0                           http://www.avatarmovie.com/   19995   
1          http://disney.go.com/disneypictures/pirates/     285   
2           http://www.sonypictures.com/mo

In [614]:
mv.head(5)

budget                                genres  \
0  237000000          [Action, Adventure, Fantasy]   
1  300000000          [Adventure, Fantasy, Action]   
2  245000000            [Action, Adventure, Crime]   
3  250000000                [Action, Crime, Drama]   
4  260000000  [Action, Adventure, Science Fiction]   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [615]:
# Change genres column into others column and id movie
columns_genres = ['id', 'unknown', 'Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
                  'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
genres_dataframe = pd.DataFrame(columns=columns_genres)
for index in mv.index:
    value = mv['id'][index]
    tmp = [value]
    for genres in columns_genres:
           if (genres != "id"):
               if genres in mv['genres'][index]:
                   tmp.append(int(1))
               else:
                   tmp.append(int(0))
    genres_dataframe.loc[len(genres_dataframe.index)] = tmp
    
genres_dataframe.head(5)

id  unknown  Action  Adventure  Animation  Children's  Comedy  Crime  \
0   19995        0       1          1          0           0       0      0   
1     285        0       1          1          0           0       0      0   
2  206647        0       1          1          0           0       0      1   
3   49026        0       1          0          0           0       0      1   
4   49529        0       1          1          0           0       0      0   

   Documentary  Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  \
0            0      0        1          0       0        0        0        0   
1            0      0        1          0       0        0        0        0   
2            0      0        0          0       0        0        0        0   
3            0      1        0          0       0        0        0        0   
4            0      0        0          0       0        0        0        0   

   Sci-Fi  Thriller  War  Western  
0       0         0    0        0  
1       0         0    0        0  
2       0         0    0        0  
3       0         0    0        0  
4       0         0    0        0

In [616]:
#change to tfidf create feature vector for items
import joblib
from sklearn.feature_extraction.text import TfidfTransformer
import pickle

transformer = TfidfTransformer(smooth_idf=True, norm ='l2')
tfidf = transformer.fit_transform(genres_dataframe.tolist()).toarray()

# store features movie vectors
joblib.dump(tfidf, 'bc_tfidf.pkl')

test = joblib.load('bc_tfidf.pkl')

print(test)

print(tfidf[[1, 2] ,:])

[[     0 0.47007135508 0.54727554242 ...      0      0      0]
 [     0 0.47007135508 0.54727554242 ...      0      0      0]
 [     0 0.50575654246 0.58882163978 ...      0      0      0]
 ...
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]
 [     0      0      0 ...      0      0      0]]
[[     0 0.47007135508 0.54727554242      0      0      0      0      0
       0 0.69247556044      0      0      0      0      0      0      0
       0      0]
 [     0 0.50575654246 0.58882163978      0      0      0 0.63047553187
       0      0      0      0      0      0      0      0      0      0
       0      0]]


In [617]:
import joblib

def store_model(model, model_name=""):
    # NOTE: sklearn.joblib faster than pickle of Python
    # INFO: can store only ONE object in a file
    if model_name == "":
        model_name = type(model).__name__
    joblib.dump(model, '../BaseContent/model_users/' + model_name + '_model.pkl')


def load_model(model_name):
    # Load objects into memory
    #del model
    model = joblib.load('../BaseContent/model_users/' + model_name + '_model.pkl')
    # print(model)
    return model

In [618]:
# get movie that rated by user
np.set_printoptions(formatter={'float': "{:6.11g}".format})


def get_items_rated_by_user(rate_matrix, user_id):
    """
    in each line of rate_matrix, we have infor: user_id, item_id, rating (scores), time_stamp
    we care about the first three values
    return (item_ids, scores) rated by user user_id

    """
    y = rate_matrix[:, 0]  # all users

    # item indices rated by user_id
    # we need to +1 to user_id since in the rate_matrix, id starts from 1
    # while index in python starts from 0

    ids = np.where(y == (user_id + 1))[0]
    tmp_ids = []
    for item in ids:
        if item.size > 0:
            tmp_ids.append(item)
    
    item_ids = rate_matrix[tmp_ids,1] - 1  # index starts from 0
   
    scores = rate_matrix[tmp_ids, 2]
    # print(ids)
    return (item_ids, scores)


In [619]:
from sklearn.linear_model import Ridge
from sklearn import linear_model

d = tfidf.shape[1]  # data dimension
W = np.zeros((d, n_users))
b = np.zeros((1, n_users))


Xhat_Large = []
scores_Larges = []
for n in range(n_users):
    ids, scores = get_items_rated_by_user(train_set, n)
    ids = ids.astype(int)

    clf = Ridge(alpha=0.01, fit_intercept=True)

    Xhat = tfidf[ids, :]
  
    for item in Xhat:
        Xhat_Large.append(item)
    for items in scores:
        scores_Larges.append(items)

    clf.fit(Xhat, scores)
  
    store_model(clf, f'User{n}')
    W[:, n] = clf.coef_
    b[0, n] = clf.intercept_
  
    


# Y = np.asarray(scores_Larges)
# X = np.asarray(np.matrix(Xhat_Large))
# print(np.matrix(Xhat_Large))
# clfLarge = Ridge(alpha=0.01, fit_intercept=True)
# clfLarge.fit(X, Y)
# store_model(clfLarge)


In [620]:
# Predict 
Yhat = tfidf.dot(W) + b
display(Yhat.shape)

(4803, 600)

In [621]:
n = 530
np.set_printoptions(precision=2) 
ids, scores = get_items_rated_by_user(train_set, n)
ids = ids.astype(int)
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', Yhat[ids, n])

Rated movies ids : [2691 1261    0  594 1720 1072 2080 3750  315  918 2161 2761 3797  157
 1014  355 4021 2290 2790  587 2705 1035 2354 4245 1379 4305 1012 1257
 2621 1652 1996 2299  660 3113 1222  540 2570 2566 3947 1182   47 4307
  499 2941 3976  585  719 1675  589  479 1847 2320 1369 1579 2423 3790
 1098 1096 2700 2053 1147 2682  363 2391 1681 1034  917 3792 1087 2796
  595]
True ratings     : [4.  1.5 3.  3.  2.  3.5 3.5 1.5 2.  4.  3.  2.  0.5 2.5 2.  3.5 3.5 4.
 0.5 4.  3.5 0.5 3.5 4.  4.  4.5 4.  0.5 3.  3.5 0.5 2.  3.5 2.5 4.  2.5
 3.5 3.5 3.5 0.5 3.  3.5 3.  4.5 2.5 2.5 4.  1.5 2.  3.  4.  3.5 0.5 3.
 2.5 4.5 1.5 3.  2.5 3.5 4.  3.  4.  3.  4.  3.5 1.5 3.5 5.  4.  3.5]
Predicted ratings: [3.06 3.09 2.62 3.14 2.38 3.48 4.19 3.38 2.62 2.98 2.73 3.09 2.96 3.07
 3.44 2.86 2.96 3.09 2.71 3.22 4.06 0.53 2.96 3.97 3.2  3.09 3.14 1.93
 2.65 2.62 2.65 2.65 3.07 2.94 3.09 3.14 3.09 3.09 2.65 2.77 2.99 3.09
 3.09 2.98 2.38 2.94 3.99 2.71 2.81 1.7  2.68 2.86 2.89 2.37 2.77 2.77
 2.54 2.71

In [622]:
from math import sqrt
def evaluate(Yhat, rates, W, b):
    se = 0
    cnt = 0
    for n in range(n_users):
        ids, scores_truth = get_items_rated_by_user(rates, n)
        ids = ids.astype(int)
        scores_pred = Yhat[ids, n]
        e = scores_truth - scores_pred 
        se += (e*e).sum(axis = 0)
        cnt += e.size 
    return sqrt(se/cnt)

In [625]:
print('RMSE for training:', evaluate(Yhat, train_set, W, b))
print('RMSE for test    :', evaluate(Yhat, test_set, W, b))


RMSE for training: 0.9014677841520674
RMSE for test    : 1.077380149870499


In [624]:
# Test load model for api

model = load_model(f"User{1}")

# tmp  = [
#     [0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0],
#     [0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0],
#     [0,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0],
#     [0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0],
#     [0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0]
# ]

# columns_genres_test_load = ['unknown', 'Action', 'Adventure', 'Animation', 'Children\'s', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy',
#                   'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
# genres_dataframe_test_load = pd.DataFrame( tmp,columns=columns_genres_test_load)

# print(genres_dataframe_test_load)
# X1 = genres_dataframe_test_load.values

# <=> yHjat = tfidf.dot(W) + b
yhat = model.predict(tfidf[[665], :])

yhat = model.predict(tfidf[ids, :])

print(yhat.shape)
print('Rated movies ids :', ids )
print('True ratings     :', scores)
print('Predicted ratings:', yhat)

Rated movies ids : [2691 1261    0  594 1720 1072 2080 3750  315  918 2161 2761 3797  157
 1014  355 4021 2290 2790  587 2705 1035 2354 4245 1379 4305 1012 1257
 2621 1652 1996 2299  660 3113 1222  540 2570 2566 3947 1182   47 4307
  499 2941 3976  585  719 1675  589  479 1847 2320 1369 1579 2423 3790
 1098 1096 2700 2053 1147 2682  363 2391 1681 1034  917 3792 1087 2796
  595]
True ratings     : [4.  1.5 3.  3.  2.  3.5 3.5 1.5 2.  4.  3.  2.  0.5 2.5 2.  3.5 3.5 4.
 0.5 4.  3.5 0.5 3.5 4.  4.  4.5 4.  0.5 3.  3.5 0.5 2.  3.5 2.5 4.  2.5
 3.5 3.5 3.5 0.5 3.  3.5 3.  4.5 2.5 2.5 4.  1.5 2.  3.  4.  3.5 0.5 3.
 2.5 4.5 1.5 3.  2.5 3.5 4.  3.  4.  3.  4.  3.5 1.5 3.5 5.  4.  3.5]
Predicted ratings: [3.32]
